version: '3'
services:
  grafana:
    image: 127.0.0.1:5000/grafana
    build:
      context: .
      dockerfile: grafana.dockerfile
    ports:
      - '3001:3000'
    deploy:
      restart_policy:
        condition: always
      resources:
        limits:
          cpus: '0.5'
          memory: '5G'
    volumes:
      - grafana-storage:/var/lib/grafana
    extra_hosts:
      - "lohsr218.driveline.gkn.com:10.133.0.77"
      - "lohsr213.driveline.gkn.com:10.133.0.78"
    environment:
      - proxy.env

volumes:
  grafana-storage:
    driver: local
